//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioAccess_TEst.BioAccessCloudBasic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresLoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LoginSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LoginSuccessful {
            get {
                return this.LoginSuccessfulField;
            }
            set {
                if ((this.LoginSuccessfulField.Equals(value) != true)) {
                    this.LoginSuccessfulField = value;
                    this.RaisePropertyChanged("LoginSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestCompleted {
            get {
                return this.RequestCompletedField;
            }
            set {
                if ((this.RequestCompletedField.Equals(value) != true)) {
                    this.RequestCompletedField = value;
                    this.RaisePropertyChanged("RequestCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.TemplateTypeBac", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresTemplateTypeBac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateTypeId {
            get {
                return this.TemplateTypeIdField;
            }
            set {
                if ((this.TemplateTypeIdField.Equals(value) != true)) {
                    this.TemplateTypeIdField = value;
                    this.RaisePropertyChanged("TemplateTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.SiteBac", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresSiteBac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> BioAccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> BioAccessId {
            get {
                return this.BioAccessIdField;
            }
            set {
                if ((this.BioAccessIdField.Equals(value) != true)) {
                    this.BioAccessIdField = value;
                    this.RaisePropertyChanged("BioAccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.EmployeeBac", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresEmployeeBac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> BioAccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RsaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateBac> TemplatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> BioAccessId {
            get {
                return this.BioAccessIdField;
            }
            set {
                if ((this.BioAccessIdField.Equals(value) != true)) {
                    this.BioAccessIdField = value;
                    this.RaisePropertyChanged("BioAccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RsaId {
            get {
                return this.RsaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RsaIdField, value) != true)) {
                    this.RsaIdField = value;
                    this.RaisePropertyChanged("RsaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateBac> Templates {
            get {
                return this.TemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatesField, value) != true)) {
                    this.TemplatesField = value;
                    this.RaisePropertyChanged("Templates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.TemplateBac", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresTemplateBac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BioAccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short FingerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BioAccessId {
            get {
                return this.BioAccessIdField;
            }
            set {
                if ((this.BioAccessIdField.Equals(value) != true)) {
                    this.BioAccessIdField = value;
                    this.RaisePropertyChanged("BioAccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short FingerNumber {
            get {
                return this.FingerNumberField;
            }
            set {
                if ((this.FingerNumberField.Equals(value) != true)) {
                    this.FingerNumberField = value;
                    this.RaisePropertyChanged("FingerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Template {
            get {
                return this.TemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateField, value) != true)) {
                    this.TemplateField = value;
                    this.RaisePropertyChanged("Template");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateType {
            get {
                return this.TemplateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateTypeField, value) != true)) {
                    this.TemplateTypeField = value;
                    this.RaisePropertyChanged("TemplateType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.GroupBac", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresGroupBac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> BioAccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> BioAccessId {
            get {
                return this.BioAccessIdField;
            }
            set {
                if ((this.BioAccessIdField.Equals(value) != true)) {
                    this.BioAccessIdField = value;
                    this.RaisePropertyChanged("BioAccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataStructures.EmployeeGroupBac", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DataStructuresEmployeeGroupBac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeGroupId {
            get {
                return this.EmployeeGroupIdField;
            }
            set {
                if ((this.EmployeeGroupIdField.Equals(value) != true)) {
                    this.EmployeeGroupIdField = value;
                    this.RaisePropertyChanged("EmployeeGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BioAccessCloudBasic.IBioAccessCloudBasic")]
    public interface IBioAccessCloudBasic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/Login", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/LoginResponse")]
        BioAccess_TEst.BioAccessCloudBasic.DataStructuresLoginResponse Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/Login", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/LoginResponse")]
        System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.DataStructuresLoginResponse> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetTemplateTypes", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetTemplateTypesResponse")]
        System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateTypeBac> GetTemplateTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetTemplateTypes", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetTemplateTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateTypeBac>> GetTemplateTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetSitesPerCustomer", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetSitesPerCustomerResponse")]
        System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> GetSitesPerCustomer(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetSitesPerCustomer", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetSitesPerCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac>> GetSitesPerCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerSite", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerSiteResponse")]
        System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> GetEmployeesPerSite(int siteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerSite", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerSiteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac>> GetEmployeesPerSiteAsync(int siteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerCustomer", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerCustomerResponse")]
        System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> GetEmployeesPerCustomer(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerCustomer", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac>> GetEmployeesPerCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateSites", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateSitesResponse")]
        BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesResponse CreateUpdateSites(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateSites", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateSitesResponse")]
        System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesResponse> CreateUpdateSitesAsync(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroups", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroupsResponse")]
        BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsResponse CreateUpdateGroups(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroups", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroupsResponse")]
        System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsResponse> CreateUpdateGroupsAsync(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroupRelations", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroupRelationsResponse")]
        string CreateUpdateGroupRelations(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeGroupBac> employeeGroups, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroupRelations", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateGroupRelationsResponse")]
        System.Threading.Tasks.Task<string> CreateUpdateGroupRelationsAsync(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeGroupBac> employeeGroups, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateTemplates", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateTemplatesResponse")]
        string CreateUpdateTemplates(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateBac> templates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateTemplates", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateTemplatesResponse")]
        System.Threading.Tasks.Task<string> CreateUpdateTemplatesAsync(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateBac> templates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateEmployees", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateEmployeesResponse")]
        BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesResponse CreateUpdateEmployees(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateEmployees", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/CreateUpdateEmployeesResponse")]
        System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesResponse> CreateUpdateEmployeesAsync(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerGroup", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerGroupResponse")]
        System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> GetEmployeesPerGroup(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerGroup", ReplyAction="http://tempuri.org/IBioAccessCloudBasic/GetEmployeesPerGroupResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac>> GetEmployeesPerGroupAsync(int groupId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdateSites", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUpdateSitesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> sites;
        
        public CreateUpdateSitesRequest() {
        }
        
        public CreateUpdateSitesRequest(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> sites) {
            this.sites = sites;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdateSitesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUpdateSitesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CreateUpdateSitesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> sites;
        
        public CreateUpdateSitesResponse() {
        }
        
        public CreateUpdateSitesResponse(string CreateUpdateSitesResult, System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> sites) {
            this.CreateUpdateSitesResult = CreateUpdateSitesResult;
            this.sites = sites;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdateGroups", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUpdateGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresGroupBac> groups;
        
        public CreateUpdateGroupsRequest() {
        }
        
        public CreateUpdateGroupsRequest(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresGroupBac> groups) {
            this.groups = groups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdateGroupsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUpdateGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CreateUpdateGroupsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresGroupBac> groups;
        
        public CreateUpdateGroupsResponse() {
        }
        
        public CreateUpdateGroupsResponse(string CreateUpdateGroupsResult, System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresGroupBac> groups) {
            this.CreateUpdateGroupsResult = CreateUpdateGroupsResult;
            this.groups = groups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdateEmployees", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUpdateEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> employees;
        
        public CreateUpdateEmployeesRequest() {
        }
        
        public CreateUpdateEmployeesRequest(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> employees) {
            this.employees = employees;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUpdateEmployeesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUpdateEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CreateUpdateEmployeesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> employees;
        
        public CreateUpdateEmployeesResponse() {
        }
        
        public CreateUpdateEmployeesResponse(string CreateUpdateEmployeesResult, System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> employees) {
            this.CreateUpdateEmployeesResult = CreateUpdateEmployeesResult;
            this.employees = employees;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBioAccessCloudBasicChannel : BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BioAccessCloudBasicClient : System.ServiceModel.ClientBase<BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic>, BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic {
        
        public BioAccessCloudBasicClient() {
        }
        
        public BioAccessCloudBasicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BioAccessCloudBasicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BioAccessCloudBasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BioAccessCloudBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BioAccess_TEst.BioAccessCloudBasic.DataStructuresLoginResponse Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.DataStructuresLoginResponse> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateTypeBac> GetTemplateTypes() {
            return base.Channel.GetTemplateTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateTypeBac>> GetTemplateTypesAsync() {
            return base.Channel.GetTemplateTypesAsync();
        }
        
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> GetSitesPerCustomer(int customerId) {
            return base.Channel.GetSitesPerCustomer(customerId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac>> GetSitesPerCustomerAsync(int customerId) {
            return base.Channel.GetSitesPerCustomerAsync(customerId);
        }
        
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> GetEmployeesPerSite(int siteId) {
            return base.Channel.GetEmployeesPerSite(siteId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac>> GetEmployeesPerSiteAsync(int siteId) {
            return base.Channel.GetEmployeesPerSiteAsync(siteId);
        }
        
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> GetEmployeesPerCustomer(int customerId) {
            return base.Channel.GetEmployeesPerCustomer(customerId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac>> GetEmployeesPerCustomerAsync(int customerId) {
            return base.Channel.GetEmployeesPerCustomerAsync(customerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesResponse BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic.CreateUpdateSites(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesRequest request) {
            return base.Channel.CreateUpdateSites(request);
        }
        
        public string CreateUpdateSites(ref System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresSiteBac> sites) {
            BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesRequest inValue = new BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesRequest();
            inValue.sites = sites;
            BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesResponse retVal = ((BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic)(this)).CreateUpdateSites(inValue);
            sites = retVal.sites;
            return retVal.CreateUpdateSitesResult;
        }
        
        public System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesResponse> CreateUpdateSitesAsync(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateSitesRequest request) {
            return base.Channel.CreateUpdateSitesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsResponse BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic.CreateUpdateGroups(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsRequest request) {
            return base.Channel.CreateUpdateGroups(request);
        }
        
        public string CreateUpdateGroups(ref System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresGroupBac> groups) {
            BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsRequest inValue = new BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsRequest();
            inValue.groups = groups;
            BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsResponse retVal = ((BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic)(this)).CreateUpdateGroups(inValue);
            groups = retVal.groups;
            return retVal.CreateUpdateGroupsResult;
        }
        
        public System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsResponse> CreateUpdateGroupsAsync(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateGroupsRequest request) {
            return base.Channel.CreateUpdateGroupsAsync(request);
        }
        
        public string CreateUpdateGroupRelations(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeGroupBac> employeeGroups, int customerId) {
            return base.Channel.CreateUpdateGroupRelations(employeeGroups, customerId);
        }
        
        public System.Threading.Tasks.Task<string> CreateUpdateGroupRelationsAsync(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeGroupBac> employeeGroups, int customerId) {
            return base.Channel.CreateUpdateGroupRelationsAsync(employeeGroups, customerId);
        }
        
        public string CreateUpdateTemplates(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateBac> templates) {
            return base.Channel.CreateUpdateTemplates(templates);
        }
        
        public System.Threading.Tasks.Task<string> CreateUpdateTemplatesAsync(System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresTemplateBac> templates) {
            return base.Channel.CreateUpdateTemplatesAsync(templates);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesResponse BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic.CreateUpdateEmployees(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesRequest request) {
            return base.Channel.CreateUpdateEmployees(request);
        }
        
        public string CreateUpdateEmployees(ref System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> employees) {
            BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesRequest inValue = new BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesRequest();
            inValue.employees = employees;
            BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesResponse retVal = ((BioAccess_TEst.BioAccessCloudBasic.IBioAccessCloudBasic)(this)).CreateUpdateEmployees(inValue);
            employees = retVal.employees;
            return retVal.CreateUpdateEmployeesResult;
        }
        
        public System.Threading.Tasks.Task<BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesResponse> CreateUpdateEmployeesAsync(BioAccess_TEst.BioAccessCloudBasic.CreateUpdateEmployeesRequest request) {
            return base.Channel.CreateUpdateEmployeesAsync(request);
        }
        
        public System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac> GetEmployeesPerGroup(int groupId) {
            return base.Channel.GetEmployeesPerGroup(groupId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BioAccess_TEst.BioAccessCloudBasic.DataStructuresEmployeeBac>> GetEmployeesPerGroupAsync(int groupId) {
            return base.Channel.GetEmployeesPerGroupAsync(groupId);
        }
    }
}
