//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Employees = new HashSet<Employee>();
            this.Groups = new HashSet<Group>();
            this.Sites = new HashSet<Site>();
        }
    
        public int Customer_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CustomerName { get; set; }
        public string VatNumber { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
