//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AttendanceTransactions = new HashSet<AttendanceTransaction>();
            this.EmployeeGroups = new HashSet<EmployeeGroup>();
            this.Templates = new HashSet<Template>();
        }
    
        public int Employee_ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public bool Active { get; set; }
        public int Customer_ID { get; set; }
        public string RSA_ID { get; set; }
        public Nullable<System.Guid> BioAccess_ID { get; set; }
        public string Employee_Number { get; set; }
    
        public virtual ICollection<AttendanceTransaction> AttendanceTransactions { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
    }
}
