//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int Site_ID { get; set; }
        public string SiteName { get; set; }
        public int Customer_ID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.Guid> BioAccess_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
